name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-ci.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-ci.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # 替换为你的Docker Hub用户名/镜像名
          images: ${{ secrets.DOCKER_USERNAME }}/rustdesk-server
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      # 仅在推送事件和合并请求时登录并推送
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          # 拉取请求时不推送，仅构建
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
